safe_parking_homepage:
    path:     /
    defaults: { _controller: SafeParkingBundle:Home:index }

safe_parking_admin_homepage:
    path:     /admin
    defaults: { _controller: SafeParkingBundle:Admin:index }

safe_parking_admin_addProprietaire:
    path:     /admin/add
    defaults: { _controller: SafeParkingBundle:Admin:addProprietaire }

safe_parking_admin_deleteProprietaire:
    path:     /admin/delete/{id}
    defaults: { _controller: SafeParkingBundle:Admin:deleteProprietaire }
    requirements:
        id: \d+

safe_parking_admin_editProprietaire:
    path:     /admin/edit/{id}
    defaults: { _controller: SafeParkingBundle:Admin:editProprietaire }
    requirements:
        id: \d+

safe_parking_login_loginpage:
    path:     /login
    defaults: { _controller: SafeParkingBundle:Login:index }

safe_parking_login_logout:
    path:     /logout
    defaults: { _controller: SafeParkingBundle:Login:logout }

safe_parking_proprietaire_homepage:
    path:     /proprietaire
    defaults: { _controller: SafeParkingBundle:Proprietaire:index }

safe_parking_proprietaire_addGarage:
    path:     /proprietaire/add/garage
    defaults: { _controller: SafeParkingBundle:Proprietaire:addGarage }

safe_parking_proprietaire_editGarage:
    path:     /proprietaire/edit/garage/{id}
    defaults: { _controller: SafeParkingBundle:Proprietaire:editGarage }
    requirements:
        id: \d+

safe_parking_proprietaire_deleteGarage:
    path:     /proprietaire/delete/garage/{id}
    defaults: { _controller: SafeParkingBundle:Proprietaire:deleteGarage }
    requirements:
        id: \d+

safe_parking_proprietaire_addGardien:
    path:     /proprietaire/add/gardien
    defaults: { _controller: SafeParkingBundle:Proprietaire:addGardien }

safe_parking_proprietaire_editGardien:
    path:     /proprietaire/edit/gardien/{id}
    defaults: { _controller: SafeParkingBundle:Proprietaire:editGardien }
    requirements:
        id: \d+

safe_parking_proprietaire_deleteGardien:
    path:     /proprietaire/delete/gardien/{id}
    defaults: { _controller: SafeParkingBundle:Proprietaire:deleteGardien }
    requirements:
        id: \d+

safe_parking_rest_gardien:
    path:     /rest/gardien/{email}/{password}
    defaults: { _controller: SafeParkingBundle:Rest:login }

safe_parking_rest_garage:
    path:     /rest/garage/{id}
    defaults: { _controller: SafeParkingBundle:Rest:info }

safe_parking_rest_garage_add:
    path:     /rest/garage/{id}/add
    defaults: { _controller: SafeParkingBundle:Rest:add }

safe_parking_rest_garage_sub:
    path:     /rest/garage/{id}/sub
    defaults: { _controller: SafeParkingBundle:Rest:sub }

safe_parking_rest_garage_add_reserve:
    path:     /rest/garage/{id}/add/reserve
    defaults: { _controller: SafeParkingBundle:Rest:addres }

safe_parking_rest_garage_sub_reserve:
    path:     /rest/garage/{id}/sub/reserve
    defaults: { _controller: SafeParkingBundle:Rest:subres }
