<?php

namespace SafeParkingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GarageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarageRepository extends EntityRepository
{
}
